server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication
    username: ragallardom
    password: modonor
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: UnaClaveMuyLargaDeAlMenos32Caracteres123456
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG